# Low-cost defaults that work on any output topology.
blur=0
blur_optimized=1
shadows=0
animations=1
gappih=5
gappiv=5
gappoh=8
gappov=8
borderpx=2
bordercolor=0x585b70ff
focuscolor=0xf5c2e7ff
urgentcolor=0xf38ba8ff
scratchpadcolor=0x89b4faff
globalcolor=0xcba6f7ff
smartgaps=1
default_mfact=0.55
default_nmaster=1
default_layout=tile
